package com.voyager.core.utils

/**
 * Internal object holding string constants used throughout the Voyager framework.
 */
internal object Constants {
    const val VISIBLE = "visible"
    const val INVISIBLE = "invisible"
    const val GONE = "gone"
    const val CENTER = "center"
    const val CENTER_HORIZONTAL = "center_horizontal"
    const val CENTER_VERTICAL = "center_vertical"
    const val LEFT = "left"
    const val RIGHT = "right"
    const val TOP = "top"
    const val BOTTOM = "bottom"
    const val START = "start"
    const val END = "end"
    const val FILL = "fill"
    const val FILL_VERTICAL = "fill_vertical"
    const val FILL_HORIZONTAL = "fill_horizontal"
    const val CLIP_VERTICAL = "clip_vertical"
    const val CLIP_HORIZONTAL = "clip_horizontal"
    const val MIDDLE = "middle"
    const val BEGINNING = "beginning"
    const val MARQUEE = "marquee"
    const val CENTER_CROP = "centerCrop"
    const val CENTER_INSIDE = "centerInside"
    const val FIT_CENTER = "fitCenter"
    const val FIT_END = "fitEnd"
    const val FIT_START = "fitStart"
    const val FIT_XY = "fitXY"
    const val MATRIX = "matrix"
    const val BOLD = "bold"
    const val ITALIC = "italic"
    const val BOLD_ITALIC = "bold|italic"
    const val TEXT_ALIGNMENT_INHERIT = "inherit"
    const val TEXT_ALIGNMENT_GRAVITY = "gravity"
    const val TEXT_ALIGNMENT_CENTER = "center"
    const val TEXT_ALIGNMENT_TEXT_START = "textStart"
    const val TEXT_ALIGNMENT_TEXT_END = "textEnd"
    const val TEXT_ALIGNMENT_VIEW_START = "viewStart"
    const val TEXT_ALIGNMENT_VIEW_END = "viewEnd"
    const val TWEEN_LOCAL_RESOURCE_STR = "@anim/"
    const val ADD = "add"
    const val MULTIPLY = "multiply"
    const val SCREEN = "screen"
    const val SRC_ATOP = "src_atop"
    const val SRC_IN = "src_in"
    const val SRC_OVER = "src_over"
    const val AUTO = "auto"
    const val HIGH = "high"
    const val LOW = "low"
    const val ALWAYS = "always"
    const val IF_CONTENT_SCROLLS = "ifContentScrolls"
    const val NEVER = "never"
    const val YES = "yes"
    const val NO = "no"
    const val NO_HIDE_DESCENDANTS = "noHideDescendants"
    const val MARGIN = "margin"
    const val TEXT = "text"
    const val HINT = "hint"
    const val MAX_WIDTH = "maxWidth"
    const val MAX_HEIGHT = "maxHeight"
    const val SHADOW_COLOR = "shadowColor"
    const val SHADOW_RADIUS = "shadowRadius"
    const val SHADOW_DX = "shadowDx"
    const val SHADOW_DY = "shadowDy"
     const val MATCH_PARENT = "match_parent"
     const val FILL_PARENT = "fill_parent"
     const val WRAP_CONTENT = "wrap_content"
} 