name: Android CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_apk:
    name: Build APK (Fastest)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository (Shallow Clone)
        uses: actions/checkout@v4
        with:
          fetch-depth: 1  # Faster Git checkout

      - name: Cache Gradle, C++ & Build Files
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.android/build-cache
            ~/.m2/repository
            .cxx  # C++ build cache
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Set up JDK 21 (Latest)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Set up Android SDK (Latest)
        uses: android-actions/setup-android@v3
        with:
          sdk-version: '35'

      - name: Set up Pre-installed NDK (No Download)
        run: |
          export ANDROID_NDK_HOME=$ANDROID_HOME/ndk/25.2.9519653
          echo "ANDROID_NDK_HOME=$ANDROID_NDK_HOME" >> $GITHUB_ENV
          echo "ANDROID_NDK=$ANDROID_NDK_HOME" >> $GITHUB_ENV
          echo "PATH=$ANDROID_NDK_HOME:$PATH" >> $GITHUB_ENV

      - name: Move Gradle & Build Files to RAM Disk (Faster Builds)
        run: |
          echo "Moving Gradle cache and build files to RAM disk (/dev/shm/)"
          mkdir -p /dev/shm/gradle-cache
          mkdir -p /dev/shm/build-cache
          mv ~/.gradle /dev/shm/gradle-cache
          mv .cxx /dev/shm/build-cache
          ln -s /dev/shm/gradle-cache ~/.gradle
          ln -s /dev/shm/build-cache .cxx

      - name: Grant Execute Permission for Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Build Native C++ Code (Optimized with Ninja)
        run: ./gradlew :app:externalNativeBuildDebug --parallel --no-daemon --build-cache --max-workers=2 --configuration-cache
        env:
          CXXFLAGS: "-O3 -flto=thin -march=native"
          CC: "clang"
          CXX: "clang++"
          CMAKE_GENERATOR: "Ninja"

      - name: Build Debug APK (Extreme Speed)
        if: ${{ github.ref == 'refs/heads/master' }}
        run: ./gradlew assembleDebug --parallel --no-daemon --build-cache --configuration-cache --max-workers=2

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-${{ github.run_number }}
          path: app/build/outputs/apk/debug/app-debug.apk
          retention-days: 10