name: Android CI Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: android-build
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code.
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up Java (Temurin JDK 21) for Android builds.
      - name: Set up Java (Temurin JDK 21)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # Step 3: Cache Gradle & Maven dependencies to speed up subsequent builds.
      - name: Cache Gradle & Maven Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.m2/repository
          key: ${{ runner.os }}-gradle-maven-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-maven-

      # Step 4: Set up Android SDK, Build Tools, and NDK.
      - name: Set up Android SDK, Build Tools, and NDK
        uses: android-actions/setup-android@v3
        with:
          sdk-version: 'latest'
          build-tools: 'latest'
          ndk-version: 'latest'

      # Step 5: Publish the Custom Gradle Plugin to GitHub Packages.
      - name: Publish Voyager Plugin
        env:
          GITHUB_USER: ${{ secrets.GITHUB_USER }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew :voyager-plugin:publishToMavenLocal --build-cache --no-daemon

      # Step 6: Build the main Android project (app) using the published plugin.
      - name: Build Android Project
        env:
          GITHUB_USER: ${{ secrets.GITHUB_USER }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew :app:assembleDebug --parallel --build-cache --configure-on-demand --no-daemon

      # Step 7: Upload the built APKs as artifacts with a retention period of 10 days.
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: APK
          path: app/build/outputs/apk/
          retention-days: 10
