name: Android CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_apk:
    name: Build Apk
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ github.token }}

      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.android/build-cache
            ~/.m2/repository
          key: ${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Set up Android SDK and NDK
        uses: android-actions/setup-android@v3
        with:
          sdk-version: '35'
          ndk-version: 'latest'

      - name: Change Gradle wrapper permissions
        run: chmod +x ./gradlew

      # --- C++ Build Steps ---
      - name: Configure CMake
        run: |
          mkdir app/.cxx
          cmake -E chdir app/.cxx cmake \
            -DANDROID_ABI="armeabi-v7a,arm64-v8a,x86,x86_64" \ # Target all common ABIs
            -DANDROID_PLATFORM=android-21 \       # Match minSdkVersion (e.g., API 21)
            -DCMAKE_TOOLCHAIN_FILE=${ANDROID_NDK_HOME}/build/cmake/android.toolchain.cmake \
            -DCMAKE_BUILD_TYPE=Debug \
            -S app/src/main/cpp \
            -B ./

      - name: Build C++ Libraries
        run: |
          cmake -E chdir app/.cxx cmake --build ./

      # --- End C++ Build Steps ---


      - name: Build Debug Apk
        if: ${{ github.ref == 'refs/heads/master' }}
        run: ./gradlew assembleDebug -Dorg.gradle.parallel=true -Dorg.gradle.daemon=true

      - name: Upload Debug
        uses: actions/upload-artifact@v4
        with:
          name: debug-${{ github.run_number }}
          path: app/build/outputs/apk/debug/app-debug.apk
          retention-days: 10