jobs:
  build_apk:
    name: Build APK (with C++)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1  

      - name: Download RapidJSON
        run: |
          git clone --depth=1 https://github.com/Tencent/rapidjson.git third_party/rapidjson
          ls third_party/rapidjson/include/rapidjson  # Check if downloaded correctly

      - name: Cache Gradle & C++ Build Files
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.android/build-cache
            .cxx
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          sdk-version: '35'

      - name: Set up Pre-installed NDK
        run: |
          export ANDROID_NDK_HOME=$ANDROID_HOME/ndk/25.2.9519653
          echo "ANDROID_NDK_HOME=$ANDROID_NDK_HOME" >> $GITHUB_ENV
          echo "ANDROID_NDK=$ANDROID_NDK_HOME" >> $GITHUB_ENV
          echo "PATH=$ANDROID_NDK_HOME:$PATH" >> $GITHUB_ENV

      - name: Grant Execute Permission for Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Build C++ Code (NDK)
        run: ./gradlew :app:externalNativeBuildDebug --parallel --no-daemon --build-cache --configuration-cache
        env:
          CXXFLAGS: "-O3 -flto=thin -march=native"
          CC: "clang"
          CXX: "clang++"
          CMAKE_GENERATOR: "Ninja"

      - name: Build Debug APK
        if: ${{ github.ref == 'refs/heads/master' }}
        run: ./gradlew assembleDebug --parallel --no-daemon --build-cache --configuration-cache

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-${{ github.run_number }}
          path: app/build/outputs/apk/debug/app-debug.apk
          retention-days: 10