name: Build Android App

on:
  push:
    branches:
      - master  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - master  # Trigger on pull requests to the main branch

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      # Step 3: Cache Gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      # Step 4: Set up Android SDK (without api-level)
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3  # No 'api-level' input needed

      # Step 5: Install Android SDK API 35 manually
      - name: Install Android SDK API 35
        run: |
          sdkmanager "platforms;android-35" "build-tools;34.0.0"

      # Step 6: Build the project
      - name: Build with Gradle
        run: ./gradlew assembleRelease

      # Step 7: Upload APK or AAB artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: app/build/outputs/apk/release/*.apk