name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_apk:
    name: Build Apk
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ github.token }}

      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.android/build-cache
            ~/.m2/repository
          key: ${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          sdk-version: '35'

      - name: Change Gradle wrapper permissions
        run: chmod +x ./gradlew

      - name: Build Debug Apk
        if: ${{ github.ref == 'refs/heads/main' }}
        run: ./gradlew assembleDebug -Dorg.gradle.parallel=true -Dorg.gradle.daemon=true

      - name: Upload Debug
        uses: actions/upload-artifact@v4
        with:
          name: debug-${{ github.run_number }}
          path: app/build/outputs/apk/debug/app-debug.apk
          retention-days: 10
